### PR TITLE
Update to current APIs, cleaning of warnings and name as parameter

### PR DESCRIPTION
**Pull request by fisica3**
After fixing Api.Bicep with the inclussion of "principalType: 'ServicePrincipal'" the deployment worked ok, but I tried to clean the unneeded parameters and update to the latest version of APIs, also I removed all the warnings and added the parameter "sufix" in order to make easier the name customization, reducing the chances of getting duplicated resources in Azure.

Hope it helps, thanks!

### CODE REVIEW

**Comment by staal-it** [comment]
Hi @fisica3! 

Thanks for creating the PR. We are currently thinking about how to merge requests like these since. We see the value of this and are grateful that you create this PR and spend your time helping us. It does however create a difference between the code in our book and this repository. We are thinking of, for example, creating separate folders or branches so that the original code can still be used and found.

So, we really appreciate your effort and will get back to this PR.

Can I ask you to keep PRs small? Could you move the changes for chapter 7 out of this PR and create a separate one?

**Comment by fisica3** [comment]
Sure, I'll remove the changes from chapter 7 since I created them after I submitted my PR, and such changes are not ready yet. 
Let me know what option you'll have to support this PR. Perhaps you can create a new branch called "updatedbicep" and I can create a new PR over it.

**Comment by fisica3** [comment]
Chapter 7 changes removed, thanks!

**Comment by henrybeen** [comment]
I'm sorry it took me so long to get to this PR. But, I went over it, deployed the templates as a verification and everything checks out. I will now merge this PR as I created a new branch with the 'book like' templates and will add to the README to explain how we want to maintain this repo and what's where.

**Pull request merged**
